; code generated by Ferrobotics Device Controller
M84 X Y Z S12000 ; set timeout
G90 ; use absolute positioning
G21 ; use milimeters
G01 X0.0 Y0.0 Z10.0 F1000.0    ; Move to [0.0, 0.0, 10.0] at speed 1000.0
G01 X30.0 Y30.0 Z10.0 F1000.0    ; Move to [30.0, 30.0, 10.0] at speed 1000.0
G01 X59.0 Y25.0 Z10.0 F1000.0    ; Move to [59.0, 25.0, 10.0] at speed 1000.0
G01 X85.0 Y56.0 Z10.0 F1000.0    ; Move to [85.0, 56.0, 10.0] at speed 1000.0
G01 X41.0 Y56.0 Z10 F1000    ; Move to [41.0, 56.0, 10] at speed 1000
G01 X41.0 Y56.0 Z10 F1000    ; Move to [41.0, 56.0, 10] at speed 1000
