; code generated by Ferrobotics Device Controller
M84 X Y Z S12000 ; set timeout
G90 ; use absolute positioning
G21 ; use milimeters
G28W ; autohome
G01 X35.0 Y32.0 Z10 F1200    ; Move to (35.0, 32.0, 10) at speed 1200
G01 X35.0 Y32.0 Z25 F1200    ; Skip to (35.0, 32.0, 25) at speed 1200
G01 X72.0 Y70.0 Z10 F1200    ; Move to (72.0, 70.0, 10) at speed 1200
G01 X72.0 Y70.0 Z25 F1200    ; Skip to (72.0, 70.0, 25) at speed 1200
G01 X132.0 Y90.0 Z10 F1200    ; Move to (132.0, 90.0, 10) at speed 1200
